#### Data laod

In [ ]:
import pandas as pd 

df = pd.read_csv(r'..\data\raw.csv')

In [2]:
df.shape

(120000, 17)

In [3]:
df.isnull().sum()

user_id               0
session_id            0
date                  0
month                 0
channel               0
campaign_type         0
device                0
user_type             0
region                0
visited_website       0
viewed_product        0
added_to_cart         0
checkout_started      0
purchase_completed    0
discount_applied      0
order_value           0
revenue               0
dtype: int64

In [4]:
df.dtypes

user_id                 int64
session_id              int64
date                      str
month                     str
channel                   str
campaign_type             str
device                    str
user_type                 str
region                    str
visited_website           str
viewed_product            str
added_to_cart             str
checkout_started          str
purchase_completed        str
discount_applied          str
order_value           float64
revenue               float64
dtype: object

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df[['order_value','revenue']].describe()

         order_value        revenue
count  120000.000000  120000.000000
mean      614.962674     141.804993
std       456.130268     545.359126
min       499.000000       0.000000
25%       499.000000       0.000000
50%       499.000000       0.000000
75%       499.000000       0.000000
max      4741.370000    4741.370000

In [7]:
df[(df['viewed_product']=='No') & (df['added_to_cart']=='Yes')]

Empty DataFrame
Columns: [user_id, session_id, date, month, channel, campaign_type, device, user_type, region, visited_website, viewed_product, added_to_cart, checkout_started, purchase_completed, discount_applied, order_value, revenue]
Index: []

In [8]:
df[(df['added_to_cart']=='No') & (df['checkout_started']=='Yes')]

Empty DataFrame
Columns: [user_id, session_id, date, month, channel, campaign_type, device, user_type, region, visited_website, viewed_product, added_to_cart, checkout_started, purchase_completed, discount_applied, order_value, revenue]
Index: []

In [9]:
df[(df['checkout_started']=='No') & (df['purchase_completed']=='Yes')]

Empty DataFrame
Columns: [user_id, session_id, date, month, channel, campaign_type, device, user_type, region, visited_website, viewed_product, added_to_cart, checkout_started, purchase_completed, discount_applied, order_value, revenue]
Index: []

In [10]:
df[df['purchase_completed']=='No']['revenue'].sum()

np.float64(0.0)

In [11]:
df['date'] = pd.to_datetime(df['date'],format='%m/%d/%Y')

In [12]:
df.columns

Index(['user_id', 'session_id', 'date', 'month', 'channel', 'campaign_type',
       'device', 'user_type', 'region', 'visited_website', 'viewed_product',
       'added_to_cart', 'checkout_started', 'purchase_completed',
       'discount_applied', 'order_value', 'revenue'],
      dtype='str')

In [ ]:
df.columns = df.columns.str.strip()

In [14]:
for col in ['channel','campaign_type','device','user_type','region']:
    print(col,df[col].unique())

channel <ArrowStringArray>
['Organic', 'Paid Ads', 'Social', 'Email']
Length: 4, dtype: str
campaign_type <ArrowStringArray>
['New Launch', 'Influencer', 'Discount']
Length: 3, dtype: str
device <ArrowStringArray>
['Mobile', 'Desktop']
Length: 2, dtype: str
user_type <ArrowStringArray>
['New', 'Returning']
Length: 2, dtype: str
region <ArrowStringArray>
['Metro', 'Non-Metro']
Length: 2, dtype: str

In [15]:
df.to_csv(r'..\data\cleaned_data.csv',index=False)

In [16]:
for col in ['channel', 'campaign_type', 'device', 'user_type', 'region']:
    print(col, df[col].unique())

channel <ArrowStringArray>
['Organic', 'Paid Ads', 'Social', 'Email']
Length: 4, dtype: str
campaign_type <ArrowStringArray>
['New Launch', 'Influencer', 'Discount']
Length: 3, dtype: str
device <ArrowStringArray>
['Mobile', 'Desktop']
Length: 2, dtype: str
user_type <ArrowStringArray>
['New', 'Returning']
Length: 2, dtype: str
region <ArrowStringArray>
['Metro', 'Non-Metro']
Length: 2, dtype: str

In [17]:
df.head()

,user_id,session_id,date,month,channel,campaign_type,device,user_type,region,visited_website,viewed_product,added_to_cart,checkout_started,purchase_completed,discount_applied,order_value,revenue
0,221958,1,2025-08-16,2025-08,Organic,New Launch,Mobile,New,Metro,Yes,No,No,No,No,No,499.00,0.000
1,771155,2,2025-12-16,2025-12,Organic,Influencer,Mobile,New,Non-Metro,Yes,Yes,Yes,No,No,No,499.00,0.000
2,231932,3,2025-07-17,2025-07,Organic,Influencer,Mobile,New,Non-Metro,Yes,Yes,No,No,No,No,499.00,0.000
3,465838,4,2025-07-04,2025-07,Paid Ads,Discount,Mobile,Returning,Metro,Yes,Yes,Yes,Yes,Yes,Yes,2000.95,1800.855
4,359178,5,2025-08-10,2025-08,Paid Ads,Influencer,Mobile,Returning,Non-Metro,Yes,No,No,No,No,No,499.00,0.000